name: ubuntu-latest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
      - name: pip upgrade
        run: |
          python -m pip install --upgrade pip & pip install --upgrade setuptools
      - name: Install six
        run: |
          pip install six
      - name: Install kss locally
        run: |
          pip install .
      - name: Run the test suite
        run: |
          pytest -v