name: ubuntu-latest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install kss locally
        run: |
          pip3 install -e .
      - name: Install pytest
        run: |
          python3 -m pip install pytest
      - name: Run the test suite
        run: |
          cd tests && pytest -v